namespace ELFeditor
{
    class MerchantStock
    {
        public List<uint[]> MerchantOffsets = new List<uint[]>();
        public uint[] Merchant1 = new uint[] { 0x27C920, 0x27C928, 0x27C930,
            0x27C938, 0x27C940, 0x27C948, 0x27C950, 0x27C958,0x27C960 };
        public uint[] Merchant2 = new uint[] { 0x27C970, 0x27C978 };
        public uint[] Merchant3 = new uint[] { 0x27C9B8, 0x27C9C0, 0x27C9C8 };
        public uint[] Merchant4 = new uint[] { 0x27CA08 };
        public uint[] Merchant5 = new uint[] { 0x27CA18, 0x27CA20, 0x27CA28, 0x27CA30, 0x27CA38, 0x27CA40, 0x27CA48,
        0x27CA50,0x27CA58, 0x27CA60,0x27CA68,0x27CA70,0x27CA78,0x27CA80,0x27CA88,0x27CA90,0x27CA98,0x27CAA0,0x27CAA8};
        public uint[] Merchant6 = new uint[] { 0x27CAC8 };
        public uint[] Merchant7 = new uint[] { 0x27CB08, 0x27CB10, 0x27CB18, 0x27CB20, 0x27CB28, 0x27CB30, 0x27CB38,
        0x27CB40, 0x27CB48,0x27CB50,0x27CB58,0x27CB60,0x27CB68,0x27CB70,0x27CB78,0x27CB80,0x27CB88,0x27CB90,0x27CB98,
        0x27CBA0,0x27CBA8};
        public uint[] Merchant8 = new uint[] { 0x27CBC0 };
        public uint[] Merchant9 = new uint[] { 0x27CBE0 };
        public uint[] Merchant10 = new uint[] { 0x27CBF0, 0x27CBF8, 0x27CC00, 0x27CC08, 0x27CC10, 0x27CC18, 0x27CC20,
            0x27CC28 };
        public uint[] Merchant11 = new uint[] { 0x27CC38 };
        public uint[] Merchant12 = new uint[] { 0x27CC50, 0x27CC58, 0x27CC60, 0x27CC68 };
        public uint[] Merchant13 = new uint[] { 0x27CC78 };
        public uint[] Merchant14 = new uint[] { 0x27CC90, 0x27CC98, 0x27CCA0 };
        public uint[] Merchant15Special = new uint[] { 0x27CCC0, 0x27CCC8, 0x27CCD8, 0x27CCE8, 0x27CCF8 };

        public void PopulateArrays()
        {
            MerchantOffsets.Add(Merchant1);
            MerchantOffsets.Add(Merchant2);
            MerchantOffsets.Add(Merchant3);
            MerchantOffsets.Add(Merchant4);
            MerchantOffsets.Add(Merchant5);
            MerchantOffsets.Add(Merchant6);
            MerchantOffsets.Add(Merchant7);
            MerchantOffsets.Add(Merchant8);
            MerchantOffsets.Add(Merchant9);
            MerchantOffsets.Add(Merchant10);
            MerchantOffsets.Add(Merchant11);
            MerchantOffsets.Add(Merchant12);
            MerchantOffsets.Add(Merchant13);
            MerchantOffsets.Add(Merchant14);
            MerchantOffsets.Add(Merchant15Special);
        }
        public List<string> ItemList = new List<string>
        {
"Magnum ammo"
,"Hand grenade"
,"Incendiary grenade"
,"Matilda"
,"Handgun ammo"
,"First aid spray"
,"Green herb"
,"rifle ammo"
,"chicken egg"
,"brown chicken egg"
,"gold chicken egg"
,"aaa"
,"plaga sample"
,"krauser's knife"
,"flash grenade"
,"salazar family insignia"
,"bowgun"
,"bowgun bolts"
,"green herb x2"
,"green herb x3"
,"mixed herbs (g+r)"
,"mixed herbs (g+r+y)"
,"mixed herbs (g+y)"
,"rocket launcher (special)"
,"shotgun shells"
,"red herb"
,"handcannon ammo"
,"hourglass w/ gold decor"
,"yellow herb"
,"stone tablet"
,"lion ornament"
,"goat ornament"
,"tmp ammo"
,"punisher"
,"punisher w/ silencer"
,"handgun"
,"handgun w/ silencer"
,"red9"
,"red9 w/ stock"
,"blacktail"
,"blacktail w/ silencer"
,"broken butterfly"
,"killer7"
,"killer7 w/ silencer"
,"shotgun"
,"striker"
,"rifle"
,"rifle (semi-auto)"
,"tmp"
,"activation key (blue)"
,"tmp w/ stock"
,"activation key (red)"
,"chicago typewriter (infinite)"
,"rocket launcher"
,"mine thrower"
,"handcannon"
,"combat knife"
,"serpent ornament"
,"moonstone (right half)"
,"insignia key"
,"round insignia"
,"false eye"
,"custom tmp"
,"silencer (handgun)"
,"silencer ???"
,"p.r.l. 412"
,"stock (red9)"
,"stock (tmp)"
,"scope (rifle)"
,"scope (semi-auto rifle)"
,"mine-darts"
,"shotgun Ada"
,"capture luis sera"
,"target practice"
,"luis' memo"
,"castellan memo"
,"female intruder"
,"butler's memo"
,"sample retrieved"
,"ritual preparation"
,"luis' memo 2"
,"rifle (semi-auto) w/ infrared scope"
,"krauser's bow"
,"chicago typewriter (regular)"
,"treasure map (castle)"
,"treasure map (island)"
,"velvet blue"
,"spinel"
,"pearl pendant"
,"brass pocket watch"
,"elegant headdress"
,"antique pipe"
,"gold bangle w/ pearls"
,"amber ring"
,"beerstein"
,"green catseye"
,"red catseye"
,"yellow catseye"
,"beerstein w/ (g)"
,"beerstein w/ (r)"
,"beerstein w/ (y)"
,"beerstein w/ (g,r)"
,"beerstein w/ (g,y)"
,"beerstein w/ (r,y)"
,"beerstein w/ (g,r,y)"
,"moonstone (left half)"
,"chicago typewriter ammo"
,"rifle + scope"
,"rifle (semi-auto) w/ scope"
,"infinite launcher"
,"king's grail"
,"queen's grail"
,"staff of royalty"
,"gold bars"
,"arrows"
,"bonus time"
,"emergency lock card key"
,"bonus points"
,"green catseye"
,"ruby"
,"treasure box (s)"
,"treasure box (l)"
,"blue moonstone"
,"key to the mine"
,"attache case s"
,"attache case m"
,"attache case l"
,"attache case xl"
,"golden sword"
,"iron key"
,"stone of sacrifice"
,"storage room card key"
,"freezer card key"
,"piece of the holy beast, panther"
,"piece of the holy beast, serpent"
,"piece of the holy beast, eagle"
,"jet-ski key"
,"dirty pearl pendant"
,"dirty brass pocket watch"
,"old key"
,"camp key"
,"dynamite"
,"lift activation key"
,"gold bangle"
,"elegant perfume bottle"
,"mirror w/ pearls & rubies"
,"waste disposal card key"
,"elegant chessboard"
,"riot gun"
,"black bass"
,"hourglass w/ gold decor"
,"black bass (l)"
,"illuminados pendant"
,"rifle w/ infrared scope"
,"crown"
,"crown jewel"
,"royal insignia"
,"crown with jewels"
,"crown with an insignia"
,"salazar family crown"
,"rifle ammo (infrared)"
,"emerald"
,"bottle caps"
,"gallery key"
,"emblem (right half)"
,"emblem (left half)"
,"hexagonal emblem"
,"castle gate key"
,"mixed herbs (r+y)"
,"treasure map (village)"
,"scope (mine-thrower)"
,"mine-thrower + scope"
,"playing manual 1"
,"info on ashley"
,"playing manual 2"
,"alert order"
,"about the blue medallions"
,"chief's note"
,"closure of the church"
,"anonymous letter"
,"playing manual 3"
,"sera and the 3rd party"
,"two routes"
,"village's last defense"
,"butterfly lamp"
,"green eye"
,"red eye"
,"blue eye"
,"butterfly lamp w/ ( g )"
,"butterfly lamp w/ ( r )"
,"butterfly lamp w/ ( b )"
,"butterfly lamp w/ ( g, r )"
,"butterfly lamp w/ ( g, b )"
,"butterfly lamp w/ ( r, b )"
,"butterfly lamp w/ ( r, g, b )"
,"prison key"
,"platinum sword"
,"infrared scope"
,"elegant mask"
,"green gem"
,"red gem"
,"purple gem"
,"elegant mask w/ ( g )"
,"elegant mask w/ ( r )"
,"elegant mask w/ ( p )"
,"elegant mask w/ ( g, r )"
,"elegant mask w/ ( g, p )"
,"elegant mask w/ ( r, p )"
,"elegant mask w/ ( r, g, p )"
,"golden lynx"
,"green stone of judgement"
,"red stone of faith"
,"blue stone of treason"
,"golden lynx w/ ( g )"
,"golden lynx w/ ( r )"
,"golden lynx w/ ( b )"
,"golden lynx w/ ( g, r )"
,"golden lynx w/ ( g, b )"
,"golden lynx w/ ( r, b )"
,"golden lynx w/ ( g, r, b )"
,"leon w/ rocket launcher"
,"leon w/ shotgun"
,"leon w/ handgun"
,"ashley graham"
,"luis sera"
,"don jose"
,"don diego"
,"don esteban"
,"don manuel"
,"dr. salvador"
,"merchant"
,"zealot w/ scythe"
,"zealot w/ shield"
,"zealot w/ bowgun"
,"leader zealot"
,"soldier w/ dynamite"
,"soldier w/ stun-rod"
,"soldier w/ hammer"
,"isabel"
,"maria"
,"ada wong"
,"bella sisters"
,"don pedro"
,"j.j."
,"letter from ada"
,"luis' memo 3"
,"paper airplane"
,"our plan"
,"luis' memo 4"
,"krauser's note"
,"luis' memo 5"
,"our mission"
,"aaa"
,"aaa"
,"tactical vest"
,"aaa"
,"punisher"
,"handgun"
,"shotgun"
,"mine thrower"
,"handcannon"
,"mine thrower + scope"
,"mission directives 1"
,"mission directives 2"
,"mission directives 3"
,"mission directives 4"
,"mission directives 5"
,"mission 1 treasure map"
,"mission 2 treasure map"
,"mission 3 treasure map"
,"mission 4 treasure map"
,"mission 5 treasure map"
        };
    }
}